version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: frontend
    networks:
      - appnet

  backend:
    build: ./backend
    container_name: backend
    expose:
      - "3000"  # only accessible internally
    networks:
      - appnet

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"  # public access
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
